export const START_LOADING = "START_LOADING"
export const STOP_LOADING = "STOP_LOADING"

export const ADD_MEETUP = "ADD_MEETUP"
export const LOAD_MEETUPS = "LOAD_MEETUPS"

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES"
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES"
